version: "3"
services:
  dockermongodb:
    image: mongo:latest
    container_name: "dockermongodb"
    ports:
      - 27017:27017
  role-service:
    image: role-service
    container_name: "role-service"
    ports:
      - 7080:7080
    links:
      - dockermongodb
