server:
  port: 7080
  servlet:
    context-path: /api/role-service
  urlPatterns: /v1/*
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  data:
    mongodb:
      database: role
  output:
    ansi:
      enabled: always
kafka:
  bootstrapServers: localhost:9092
  topic: roleTopic
cpfService:
  enabled: true
  url: https://user-info.herokuapp.com/users/
