server:
  port: 7080
  servlet:
    context-path: /api/role-service
  urlPatterns: /v1/*
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  data:
    mongodb:
      database: role
  output:
    ansi:
      enabled: always
